
namespace WholeSaleManagementSystem
{
    partial class Customer_Signup
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Customer_Signup));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.dobErr = new System.Windows.Forms.Label();
            this.dobDatePicker = new System.Windows.Forms.DateTimePicker();
            this.lastNameErr = new System.Windows.Forms.Label();
            this.lastName_textBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.goto_login_Button = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.cpasswordErr = new System.Windows.Forms.Label();
            this.passwordErr = new System.Windows.Forms.Label();
            this.useridErr = new System.Windows.Forms.Label();
            this.phoneErr = new System.Windows.Forms.Label();
            this.emailErr = new System.Windows.Forms.Label();
            this.firstNameErr = new System.Windows.Forms.Label();
            this.cpassword_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.userid_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.phone_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.email_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.Logo = new System.Windows.Forms.Label();
            this.Clear = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.SignUpButton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.password_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.firstName_textbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LogInFormEllips = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.Minimize = new Bunifu.UI.WinForms.BunifuImageButton();
            this.Exit = new Bunifu.UI.WinForms.BunifuImageButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.dobErr);
            this.panel1.Controls.Add(this.dobDatePicker);
            this.panel1.Controls.Add(this.lastNameErr);
            this.panel1.Controls.Add(this.lastName_textBox);
            this.panel1.Controls.Add(this.goto_login_Button);
            this.panel1.Controls.Add(this.cpasswordErr);
            this.panel1.Controls.Add(this.passwordErr);
            this.panel1.Controls.Add(this.useridErr);
            this.panel1.Controls.Add(this.phoneErr);
            this.panel1.Controls.Add(this.emailErr);
            this.panel1.Controls.Add(this.firstNameErr);
            this.panel1.Controls.Add(this.cpassword_textbox);
            this.panel1.Controls.Add(this.userid_textbox);
            this.panel1.Controls.Add(this.phone_textbox);
            this.panel1.Controls.Add(this.email_textbox);
            this.panel1.Controls.Add(this.Logo);
            this.panel1.Controls.Add(this.Clear);
            this.panel1.Controls.Add(this.SignUpButton);
            this.panel1.Controls.Add(this.password_textbox);
            this.panel1.Controls.Add(this.firstName_textbox);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(10, 49);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(621, 489);
            this.panel1.TabIndex = 1;
            // 
            // dobErr
            // 
            this.dobErr.AutoSize = true;
            this.dobErr.ForeColor = System.Drawing.Color.Red;
            this.dobErr.Location = new System.Drawing.Point(56, 229);
            this.dobErr.Name = "dobErr";
            this.dobErr.Size = new System.Drawing.Size(0, 13);
            this.dobErr.TabIndex = 21;
            // 
            // dobDatePicker
            // 
            this.dobDatePicker.CalendarFont = new System.Drawing.Font("Century Gothic", 9.75F);
            this.dobDatePicker.CalendarForeColor = System.Drawing.Color.DarkMagenta;
            this.dobDatePicker.Checked = false;
            this.dobDatePicker.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.dobDatePicker.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dobDatePicker.Location = new System.Drawing.Point(38, 203);
            this.dobDatePicker.Name = "dobDatePicker";
            this.dobDatePicker.Size = new System.Drawing.Size(234, 23);
            this.dobDatePicker.TabIndex = 4;
            this.dobDatePicker.Value = new System.DateTime(2022, 12, 30, 0, 0, 0, 0);
            this.dobDatePicker.CloseUp += new System.EventHandler(this.dobDatePicker_CloseUp);
            this.dobDatePicker.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.dobDatePicker_KeyPress);
            // 
            // lastNameErr
            // 
            this.lastNameErr.AutoSize = true;
            this.lastNameErr.ForeColor = System.Drawing.Color.Red;
            this.lastNameErr.Location = new System.Drawing.Point(343, 107);
            this.lastNameErr.Name = "lastNameErr";
            this.lastNameErr.Size = new System.Drawing.Size(0, 13);
            this.lastNameErr.TabIndex = 19;
            // 
            // lastName_textBox
            // 
            this.lastName_textBox.AcceptsReturn = false;
            this.lastName_textBox.AcceptsTab = false;
            this.lastName_textBox.AnimationSpeed = 200;
            this.lastName_textBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastName_textBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastName_textBox.BackColor = System.Drawing.Color.White;
            this.lastName_textBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastName_textBox.BackgroundImage")));
            this.lastName_textBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.lastName_textBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastName_textBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.lastName_textBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastName_textBox.BorderRadius = 10;
            this.lastName_textBox.BorderThickness = 1;
            this.lastName_textBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastName_textBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastName_textBox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lastName_textBox.DefaultText = "";
            this.lastName_textBox.FillColor = System.Drawing.Color.White;
            this.lastName_textBox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.lastName_textBox.HideSelection = true;
            this.lastName_textBox.IconLeft = null;
            this.lastName_textBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastName_textBox.IconPadding = 10;
            this.lastName_textBox.IconRight = null;
            this.lastName_textBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastName_textBox.Lines = new string[0];
            this.lastName_textBox.Location = new System.Drawing.Point(325, 73);
            this.lastName_textBox.MaxLength = 32767;
            this.lastName_textBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastName_textBox.Modified = false;
            this.lastName_textBox.Multiline = false;
            this.lastName_textBox.Name = "lastName_textBox";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastName_textBox.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastName_textBox.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastName_textBox.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastName_textBox.OnIdleState = stateProperties4;
            this.lastName_textBox.Padding = new System.Windows.Forms.Padding(3);
            this.lastName_textBox.PasswordChar = '\0';
            this.lastName_textBox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastName_textBox.PlaceholderText = "Enter Last Name";
            this.lastName_textBox.ReadOnly = false;
            this.lastName_textBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastName_textBox.SelectedText = "";
            this.lastName_textBox.SelectionLength = 0;
            this.lastName_textBox.SelectionStart = 0;
            this.lastName_textBox.ShortcutsEnabled = true;
            this.lastName_textBox.Size = new System.Drawing.Size(234, 31);
            this.lastName_textBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastName_textBox.TabIndex = 1;
            this.lastName_textBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastName_textBox.TextMarginBottom = 0;
            this.lastName_textBox.TextMarginLeft = 3;
            this.lastName_textBox.TextMarginTop = 0;
            this.lastName_textBox.TextPlaceholder = "Enter Last Name";
            this.lastName_textBox.UseSystemPasswordChar = false;
            this.lastName_textBox.WordWrap = true;
            this.lastName_textBox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.lastName_textBox_KeyDown);
            // 
            // goto_login_Button
            // 
            this.goto_login_Button.AllowAnimations = true;
            this.goto_login_Button.AllowMouseEffects = true;
            this.goto_login_Button.AllowToggling = false;
            this.goto_login_Button.AnimationSpeed = 200;
            this.goto_login_Button.AutoGenerateColors = false;
            this.goto_login_Button.AutoRoundBorders = false;
            this.goto_login_Button.AutoSizeLeftIcon = true;
            this.goto_login_Button.AutoSizeRightIcon = true;
            this.goto_login_Button.BackColor = System.Drawing.Color.Transparent;
            this.goto_login_Button.BackColor1 = System.Drawing.Color.Transparent;
            this.goto_login_Button.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("goto_login_Button.BackgroundImage")));
            this.goto_login_Button.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goto_login_Button.ButtonText = "Goto Login";
            this.goto_login_Button.ButtonTextMarginLeft = 0;
            this.goto_login_Button.ColorContrastOnClick = 45;
            this.goto_login_Button.ColorContrastOnHover = 45;
            this.goto_login_Button.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.goto_login_Button.CustomizableEdges = borderEdges1;
            this.goto_login_Button.DialogResult = System.Windows.Forms.DialogResult.None;
            this.goto_login_Button.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.goto_login_Button.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.goto_login_Button.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.goto_login_Button.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.goto_login_Button.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.goto_login_Button.ForeColor = System.Drawing.Color.DarkMagenta;
            this.goto_login_Button.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.goto_login_Button.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.goto_login_Button.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.goto_login_Button.IconMarginLeft = 11;
            this.goto_login_Button.IconPadding = 10;
            this.goto_login_Button.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.goto_login_Button.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.goto_login_Button.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.goto_login_Button.IconSize = 25;
            this.goto_login_Button.IdleBorderColor = System.Drawing.Color.Transparent;
            this.goto_login_Button.IdleBorderRadius = 1;
            this.goto_login_Button.IdleBorderThickness = 1;
            this.goto_login_Button.IdleFillColor = System.Drawing.Color.Transparent;
            this.goto_login_Button.IdleIconLeftImage = null;
            this.goto_login_Button.IdleIconRightImage = null;
            this.goto_login_Button.IndicateFocus = false;
            this.goto_login_Button.Location = new System.Drawing.Point(241, 395);
            this.goto_login_Button.Name = "goto_login_Button";
            this.goto_login_Button.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.goto_login_Button.OnDisabledState.BorderRadius = 1;
            this.goto_login_Button.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goto_login_Button.OnDisabledState.BorderThickness = 1;
            this.goto_login_Button.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.goto_login_Button.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.goto_login_Button.OnDisabledState.IconLeftImage = null;
            this.goto_login_Button.OnDisabledState.IconRightImage = null;
            this.goto_login_Button.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.goto_login_Button.onHoverState.BorderRadius = 1;
            this.goto_login_Button.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goto_login_Button.onHoverState.BorderThickness = 1;
            this.goto_login_Button.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.goto_login_Button.onHoverState.ForeColor = System.Drawing.Color.White;
            this.goto_login_Button.onHoverState.IconLeftImage = null;
            this.goto_login_Button.onHoverState.IconRightImage = null;
            this.goto_login_Button.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.goto_login_Button.OnIdleState.BorderRadius = 1;
            this.goto_login_Button.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goto_login_Button.OnIdleState.BorderThickness = 1;
            this.goto_login_Button.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.goto_login_Button.OnIdleState.ForeColor = System.Drawing.Color.DarkMagenta;
            this.goto_login_Button.OnIdleState.IconLeftImage = null;
            this.goto_login_Button.OnIdleState.IconRightImage = null;
            this.goto_login_Button.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.goto_login_Button.OnPressedState.BorderRadius = 1;
            this.goto_login_Button.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.goto_login_Button.OnPressedState.BorderThickness = 1;
            this.goto_login_Button.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.goto_login_Button.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.goto_login_Button.OnPressedState.IconLeftImage = null;
            this.goto_login_Button.OnPressedState.IconRightImage = null;
            this.goto_login_Button.Size = new System.Drawing.Size(140, 26);
            this.goto_login_Button.TabIndex = 10;
            this.goto_login_Button.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.goto_login_Button.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.goto_login_Button.TextMarginLeft = 0;
            this.goto_login_Button.TextPadding = new System.Windows.Forms.Padding(0);
            this.goto_login_Button.UseDefaultRadiusAndThickness = true;
            this.goto_login_Button.Click += new System.EventHandler(this.goto_login_Button_Click);
            // 
            // cpasswordErr
            // 
            this.cpasswordErr.AutoSize = true;
            this.cpasswordErr.ForeColor = System.Drawing.Color.Red;
            this.cpasswordErr.Location = new System.Drawing.Point(343, 302);
            this.cpasswordErr.Name = "cpasswordErr";
            this.cpasswordErr.Size = new System.Drawing.Size(0, 13);
            this.cpasswordErr.TabIndex = 16;
            // 
            // passwordErr
            // 
            this.passwordErr.AutoSize = true;
            this.passwordErr.ForeColor = System.Drawing.Color.Red;
            this.passwordErr.Location = new System.Drawing.Point(56, 302);
            this.passwordErr.Name = "passwordErr";
            this.passwordErr.Size = new System.Drawing.Size(0, 13);
            this.passwordErr.TabIndex = 15;
            // 
            // useridErr
            // 
            this.useridErr.AutoSize = true;
            this.useridErr.ForeColor = System.Drawing.Color.Red;
            this.useridErr.Location = new System.Drawing.Point(342, 237);
            this.useridErr.Name = "useridErr";
            this.useridErr.Size = new System.Drawing.Size(0, 13);
            this.useridErr.TabIndex = 14;
            // 
            // phoneErr
            // 
            this.phoneErr.AutoSize = true;
            this.phoneErr.ForeColor = System.Drawing.Color.Red;
            this.phoneErr.Location = new System.Drawing.Point(343, 173);
            this.phoneErr.Name = "phoneErr";
            this.phoneErr.Size = new System.Drawing.Size(0, 13);
            this.phoneErr.TabIndex = 13;
            // 
            // emailErr
            // 
            this.emailErr.AutoSize = true;
            this.emailErr.ForeColor = System.Drawing.Color.Red;
            this.emailErr.Location = new System.Drawing.Point(55, 173);
            this.emailErr.Name = "emailErr";
            this.emailErr.Size = new System.Drawing.Size(0, 13);
            this.emailErr.TabIndex = 12;
            // 
            // firstNameErr
            // 
            this.firstNameErr.AutoSize = true;
            this.firstNameErr.ForeColor = System.Drawing.Color.Red;
            this.firstNameErr.Location = new System.Drawing.Point(55, 107);
            this.firstNameErr.Name = "firstNameErr";
            this.firstNameErr.Size = new System.Drawing.Size(0, 13);
            this.firstNameErr.TabIndex = 11;
            // 
            // cpassword_textbox
            // 
            this.cpassword_textbox.AcceptsReturn = false;
            this.cpassword_textbox.AcceptsTab = false;
            this.cpassword_textbox.AnimationSpeed = 200;
            this.cpassword_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.cpassword_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.cpassword_textbox.BackColor = System.Drawing.Color.White;
            this.cpassword_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("cpassword_textbox.BackgroundImage")));
            this.cpassword_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.cpassword_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cpassword_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.cpassword_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.cpassword_textbox.BorderRadius = 10;
            this.cpassword_textbox.BorderThickness = 1;
            this.cpassword_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.cpassword_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.cpassword_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.cpassword_textbox.DefaultText = "";
            this.cpassword_textbox.FillColor = System.Drawing.Color.White;
            this.cpassword_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.cpassword_textbox.HideSelection = true;
            this.cpassword_textbox.IconLeft = null;
            this.cpassword_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpassword_textbox.IconPadding = 10;
            this.cpassword_textbox.IconRight = null;
            this.cpassword_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.cpassword_textbox.Lines = new string[0];
            this.cpassword_textbox.Location = new System.Drawing.Point(325, 268);
            this.cpassword_textbox.MaxLength = 32767;
            this.cpassword_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.cpassword_textbox.Modified = false;
            this.cpassword_textbox.Multiline = false;
            this.cpassword_textbox.Name = "cpassword_textbox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpassword_textbox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.cpassword_textbox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpassword_textbox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.cpassword_textbox.OnIdleState = stateProperties8;
            this.cpassword_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.cpassword_textbox.PasswordChar = '●';
            this.cpassword_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.cpassword_textbox.PlaceholderText = "Confirm Passowrd";
            this.cpassword_textbox.ReadOnly = false;
            this.cpassword_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.cpassword_textbox.SelectedText = "";
            this.cpassword_textbox.SelectionLength = 0;
            this.cpassword_textbox.SelectionStart = 0;
            this.cpassword_textbox.ShortcutsEnabled = true;
            this.cpassword_textbox.Size = new System.Drawing.Size(234, 31);
            this.cpassword_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.cpassword_textbox.TabIndex = 7;
            this.cpassword_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.cpassword_textbox.TextMarginBottom = 0;
            this.cpassword_textbox.TextMarginLeft = 3;
            this.cpassword_textbox.TextMarginTop = 0;
            this.cpassword_textbox.TextPlaceholder = "Confirm Passowrd";
            this.cpassword_textbox.UseSystemPasswordChar = true;
            this.cpassword_textbox.WordWrap = true;
            this.cpassword_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.cpassword_textbox_KeyDown);
            // 
            // userid_textbox
            // 
            this.userid_textbox.AcceptsReturn = false;
            this.userid_textbox.AcceptsTab = false;
            this.userid_textbox.AnimationSpeed = 200;
            this.userid_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.userid_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.userid_textbox.BackColor = System.Drawing.Color.White;
            this.userid_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("userid_textbox.BackgroundImage")));
            this.userid_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.userid_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.userid_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.userid_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.userid_textbox.BorderRadius = 10;
            this.userid_textbox.BorderThickness = 1;
            this.userid_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.userid_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.userid_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.userid_textbox.DefaultText = "";
            this.userid_textbox.FillColor = System.Drawing.Color.White;
            this.userid_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.userid_textbox.HideSelection = true;
            this.userid_textbox.IconLeft = null;
            this.userid_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.userid_textbox.IconPadding = 10;
            this.userid_textbox.IconRight = null;
            this.userid_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.userid_textbox.Lines = new string[0];
            this.userid_textbox.Location = new System.Drawing.Point(325, 203);
            this.userid_textbox.MaxLength = 32767;
            this.userid_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.userid_textbox.Modified = false;
            this.userid_textbox.Multiline = false;
            this.userid_textbox.Name = "userid_textbox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userid_textbox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.userid_textbox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userid_textbox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.userid_textbox.OnIdleState = stateProperties12;
            this.userid_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.userid_textbox.PasswordChar = '\0';
            this.userid_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.userid_textbox.PlaceholderText = "Choose User ID";
            this.userid_textbox.ReadOnly = false;
            this.userid_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.userid_textbox.SelectedText = "";
            this.userid_textbox.SelectionLength = 0;
            this.userid_textbox.SelectionStart = 0;
            this.userid_textbox.ShortcutsEnabled = true;
            this.userid_textbox.Size = new System.Drawing.Size(234, 31);
            this.userid_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.userid_textbox.TabIndex = 5;
            this.userid_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.userid_textbox.TextMarginBottom = 0;
            this.userid_textbox.TextMarginLeft = 3;
            this.userid_textbox.TextMarginTop = 0;
            this.userid_textbox.TextPlaceholder = "Choose User ID";
            this.userid_textbox.UseSystemPasswordChar = false;
            this.userid_textbox.WordWrap = true;
            this.userid_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.userid_textbox_KeyDown);
            // 
            // phone_textbox
            // 
            this.phone_textbox.AcceptsReturn = false;
            this.phone_textbox.AcceptsTab = false;
            this.phone_textbox.AnimationSpeed = 200;
            this.phone_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.phone_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.phone_textbox.BackColor = System.Drawing.Color.White;
            this.phone_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("phone_textbox.BackgroundImage")));
            this.phone_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.phone_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.phone_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.phone_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.phone_textbox.BorderRadius = 10;
            this.phone_textbox.BorderThickness = 1;
            this.phone_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.phone_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.phone_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.phone_textbox.DefaultText = "";
            this.phone_textbox.FillColor = System.Drawing.Color.White;
            this.phone_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.phone_textbox.HideSelection = true;
            this.phone_textbox.IconLeft = null;
            this.phone_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone_textbox.IconPadding = 10;
            this.phone_textbox.IconRight = null;
            this.phone_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.phone_textbox.Lines = new string[0];
            this.phone_textbox.Location = new System.Drawing.Point(325, 139);
            this.phone_textbox.MaxLength = 32767;
            this.phone_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.phone_textbox.Modified = false;
            this.phone_textbox.Multiline = false;
            this.phone_textbox.Name = "phone_textbox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone_textbox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.phone_textbox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone_textbox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.phone_textbox.OnIdleState = stateProperties16;
            this.phone_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.phone_textbox.PasswordChar = '\0';
            this.phone_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.phone_textbox.PlaceholderText = "Enter Phone";
            this.phone_textbox.ReadOnly = false;
            this.phone_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.phone_textbox.SelectedText = "";
            this.phone_textbox.SelectionLength = 0;
            this.phone_textbox.SelectionStart = 0;
            this.phone_textbox.ShortcutsEnabled = true;
            this.phone_textbox.Size = new System.Drawing.Size(234, 31);
            this.phone_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.phone_textbox.TabIndex = 3;
            this.phone_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.phone_textbox.TextMarginBottom = 0;
            this.phone_textbox.TextMarginLeft = 3;
            this.phone_textbox.TextMarginTop = 0;
            this.phone_textbox.TextPlaceholder = "Enter Phone";
            this.phone_textbox.UseSystemPasswordChar = false;
            this.phone_textbox.WordWrap = true;
            this.phone_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.phone_textbox_KeyDown);
            // 
            // email_textbox
            // 
            this.email_textbox.AcceptsReturn = false;
            this.email_textbox.AcceptsTab = false;
            this.email_textbox.AnimationSpeed = 200;
            this.email_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.email_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.email_textbox.BackColor = System.Drawing.Color.White;
            this.email_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("email_textbox.BackgroundImage")));
            this.email_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.email_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.email_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.email_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.email_textbox.BorderRadius = 10;
            this.email_textbox.BorderThickness = 1;
            this.email_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.email_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.email_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.email_textbox.DefaultText = "";
            this.email_textbox.FillColor = System.Drawing.Color.White;
            this.email_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.email_textbox.HideSelection = true;
            this.email_textbox.IconLeft = null;
            this.email_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.email_textbox.IconPadding = 10;
            this.email_textbox.IconRight = null;
            this.email_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.email_textbox.Lines = new string[0];
            this.email_textbox.Location = new System.Drawing.Point(38, 139);
            this.email_textbox.MaxLength = 32767;
            this.email_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.email_textbox.Modified = false;
            this.email_textbox.Multiline = false;
            this.email_textbox.Name = "email_textbox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_textbox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.email_textbox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_textbox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.email_textbox.OnIdleState = stateProperties20;
            this.email_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.email_textbox.PasswordChar = '\0';
            this.email_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.email_textbox.PlaceholderText = "Enter Email";
            this.email_textbox.ReadOnly = false;
            this.email_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.email_textbox.SelectedText = "";
            this.email_textbox.SelectionLength = 0;
            this.email_textbox.SelectionStart = 0;
            this.email_textbox.ShortcutsEnabled = true;
            this.email_textbox.Size = new System.Drawing.Size(234, 31);
            this.email_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.email_textbox.TabIndex = 2;
            this.email_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.email_textbox.TextMarginBottom = 0;
            this.email_textbox.TextMarginLeft = 3;
            this.email_textbox.TextMarginTop = 0;
            this.email_textbox.TextPlaceholder = "Enter Email";
            this.email_textbox.UseSystemPasswordChar = false;
            this.email_textbox.WordWrap = true;
            this.email_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.email_textbox_KeyDown);
            // 
            // Logo
            // 
            this.Logo.AutoSize = true;
            this.Logo.Font = new System.Drawing.Font("Century Gothic", 14F, System.Drawing.FontStyle.Bold);
            this.Logo.ForeColor = System.Drawing.Color.DarkMagenta;
            this.Logo.Location = new System.Drawing.Point(180, 13);
            this.Logo.Name = "Logo";
            this.Logo.Size = new System.Drawing.Size(233, 23);
            this.Logo.TabIndex = 10;
            this.Logo.Text = "WholeSaleManagement";
            // 
            // Clear
            // 
            this.Clear.AllowAnimations = true;
            this.Clear.AllowMouseEffects = true;
            this.Clear.AllowToggling = false;
            this.Clear.AnimationSpeed = 200;
            this.Clear.AutoGenerateColors = false;
            this.Clear.AutoRoundBorders = false;
            this.Clear.AutoSizeLeftIcon = true;
            this.Clear.AutoSizeRightIcon = true;
            this.Clear.BackColor = System.Drawing.Color.Transparent;
            this.Clear.BackColor1 = System.Drawing.Color.Transparent;
            this.Clear.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Clear.BackgroundImage")));
            this.Clear.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Clear.ButtonText = "Clear";
            this.Clear.ButtonTextMarginLeft = 0;
            this.Clear.ColorContrastOnClick = 45;
            this.Clear.ColorContrastOnHover = 45;
            this.Clear.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.Clear.CustomizableEdges = borderEdges2;
            this.Clear.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Clear.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Clear.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Clear.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Clear.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Clear.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold);
            this.Clear.ForeColor = System.Drawing.Color.DarkMagenta;
            this.Clear.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Clear.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Clear.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Clear.IconMarginLeft = 11;
            this.Clear.IconPadding = 10;
            this.Clear.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Clear.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Clear.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Clear.IconSize = 25;
            this.Clear.IdleBorderColor = System.Drawing.Color.Transparent;
            this.Clear.IdleBorderRadius = 7;
            this.Clear.IdleBorderThickness = 1;
            this.Clear.IdleFillColor = System.Drawing.Color.Transparent;
            this.Clear.IdleIconLeftImage = null;
            this.Clear.IdleIconRightImage = null;
            this.Clear.IndicateFocus = false;
            this.Clear.Location = new System.Drawing.Point(349, 363);
            this.Clear.Name = "Clear";
            this.Clear.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Clear.OnDisabledState.BorderRadius = 7;
            this.Clear.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Clear.OnDisabledState.BorderThickness = 1;
            this.Clear.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Clear.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Clear.OnDisabledState.IconLeftImage = null;
            this.Clear.OnDisabledState.IconRightImage = null;
            this.Clear.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Clear.onHoverState.BorderRadius = 7;
            this.Clear.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Clear.onHoverState.BorderThickness = 1;
            this.Clear.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Clear.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Clear.onHoverState.IconLeftImage = null;
            this.Clear.onHoverState.IconRightImage = null;
            this.Clear.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.Clear.OnIdleState.BorderRadius = 7;
            this.Clear.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Clear.OnIdleState.BorderThickness = 1;
            this.Clear.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Clear.OnIdleState.ForeColor = System.Drawing.Color.DarkMagenta;
            this.Clear.OnIdleState.IconLeftImage = null;
            this.Clear.OnIdleState.IconRightImage = null;
            this.Clear.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Clear.OnPressedState.BorderRadius = 7;
            this.Clear.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Clear.OnPressedState.BorderThickness = 1;
            this.Clear.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Clear.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Clear.OnPressedState.IconLeftImage = null;
            this.Clear.OnPressedState.IconRightImage = null;
            this.Clear.Size = new System.Drawing.Size(93, 26);
            this.Clear.TabIndex = 9;
            this.Clear.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Clear.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Clear.TextMarginLeft = 0;
            this.Clear.TextPadding = new System.Windows.Forms.Padding(0);
            this.Clear.UseDefaultRadiusAndThickness = true;
            this.Clear.Click += new System.EventHandler(this.Clear_Click_1);
            // 
            // SignUpButton
            // 
            this.SignUpButton.AllowAnimations = true;
            this.SignUpButton.AllowMouseEffects = true;
            this.SignUpButton.AllowToggling = false;
            this.SignUpButton.AnimationSpeed = 200;
            this.SignUpButton.AutoGenerateColors = false;
            this.SignUpButton.AutoRoundBorders = false;
            this.SignUpButton.AutoSizeLeftIcon = true;
            this.SignUpButton.AutoSizeRightIcon = true;
            this.SignUpButton.BackColor = System.Drawing.Color.Transparent;
            this.SignUpButton.BackColor1 = System.Drawing.Color.DarkMagenta;
            this.SignUpButton.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("SignUpButton.BackgroundImage")));
            this.SignUpButton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SignUpButton.ButtonText = "Signup";
            this.SignUpButton.ButtonTextMarginLeft = 0;
            this.SignUpButton.ColorContrastOnClick = 45;
            this.SignUpButton.ColorContrastOnHover = 45;
            this.SignUpButton.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.SignUpButton.CustomizableEdges = borderEdges3;
            this.SignUpButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.SignUpButton.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SignUpButton.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SignUpButton.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SignUpButton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.SignUpButton.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.SignUpButton.ForeColor = System.Drawing.Color.White;
            this.SignUpButton.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.SignUpButton.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.SignUpButton.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.SignUpButton.IconMarginLeft = 11;
            this.SignUpButton.IconPadding = 10;
            this.SignUpButton.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.SignUpButton.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.SignUpButton.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.SignUpButton.IconSize = 25;
            this.SignUpButton.IdleBorderColor = System.Drawing.Color.DarkMagenta;
            this.SignUpButton.IdleBorderRadius = 7;
            this.SignUpButton.IdleBorderThickness = 1;
            this.SignUpButton.IdleFillColor = System.Drawing.Color.DarkMagenta;
            this.SignUpButton.IdleIconLeftImage = null;
            this.SignUpButton.IdleIconRightImage = null;
            this.SignUpButton.IndicateFocus = false;
            this.SignUpButton.Location = new System.Drawing.Point(109, 350);
            this.SignUpButton.Name = "SignUpButton";
            this.SignUpButton.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.SignUpButton.OnDisabledState.BorderRadius = 7;
            this.SignUpButton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SignUpButton.OnDisabledState.BorderThickness = 1;
            this.SignUpButton.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.SignUpButton.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.SignUpButton.OnDisabledState.IconLeftImage = null;
            this.SignUpButton.OnDisabledState.IconRightImage = null;
            this.SignUpButton.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SignUpButton.onHoverState.BorderRadius = 7;
            this.SignUpButton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SignUpButton.onHoverState.BorderThickness = 1;
            this.SignUpButton.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.SignUpButton.onHoverState.ForeColor = System.Drawing.Color.White;
            this.SignUpButton.onHoverState.IconLeftImage = null;
            this.SignUpButton.onHoverState.IconRightImage = null;
            this.SignUpButton.OnIdleState.BorderColor = System.Drawing.Color.DarkMagenta;
            this.SignUpButton.OnIdleState.BorderRadius = 7;
            this.SignUpButton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SignUpButton.OnIdleState.BorderThickness = 1;
            this.SignUpButton.OnIdleState.FillColor = System.Drawing.Color.DarkMagenta;
            this.SignUpButton.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.SignUpButton.OnIdleState.IconLeftImage = null;
            this.SignUpButton.OnIdleState.IconRightImage = null;
            this.SignUpButton.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SignUpButton.OnPressedState.BorderRadius = 7;
            this.SignUpButton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.SignUpButton.OnPressedState.BorderThickness = 1;
            this.SignUpButton.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.SignUpButton.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.SignUpButton.OnPressedState.IconLeftImage = null;
            this.SignUpButton.OnPressedState.IconRightImage = null;
            this.SignUpButton.Size = new System.Drawing.Size(234, 39);
            this.SignUpButton.TabIndex = 8;
            this.SignUpButton.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.SignUpButton.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.SignUpButton.TextMarginLeft = 0;
            this.SignUpButton.TextPadding = new System.Windows.Forms.Padding(0);
            this.SignUpButton.UseDefaultRadiusAndThickness = true;
            this.SignUpButton.Click += new System.EventHandler(this.SignUpButton_Click_1);
            // 
            // password_textbox
            // 
            this.password_textbox.AcceptsReturn = false;
            this.password_textbox.AcceptsTab = false;
            this.password_textbox.AnimationSpeed = 200;
            this.password_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.password_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.password_textbox.BackColor = System.Drawing.Color.White;
            this.password_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("password_textbox.BackgroundImage")));
            this.password_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.password_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.password_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.password_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.password_textbox.BorderRadius = 10;
            this.password_textbox.BorderThickness = 1;
            this.password_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.password_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.password_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.password_textbox.DefaultText = "";
            this.password_textbox.FillColor = System.Drawing.Color.White;
            this.password_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.password_textbox.HideSelection = true;
            this.password_textbox.IconLeft = null;
            this.password_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.password_textbox.IconPadding = 10;
            this.password_textbox.IconRight = null;
            this.password_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.password_textbox.Lines = new string[0];
            this.password_textbox.Location = new System.Drawing.Point(38, 268);
            this.password_textbox.MaxLength = 32767;
            this.password_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.password_textbox.Modified = false;
            this.password_textbox.Multiline = false;
            this.password_textbox.Name = "password_textbox";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_textbox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.password_textbox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_textbox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.password_textbox.OnIdleState = stateProperties24;
            this.password_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.password_textbox.PasswordChar = '●';
            this.password_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.password_textbox.PlaceholderText = "Enter Pasword";
            this.password_textbox.ReadOnly = false;
            this.password_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.password_textbox.SelectedText = "";
            this.password_textbox.SelectionLength = 0;
            this.password_textbox.SelectionStart = 0;
            this.password_textbox.ShortcutsEnabled = true;
            this.password_textbox.Size = new System.Drawing.Size(234, 31);
            this.password_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.password_textbox.TabIndex = 6;
            this.password_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.password_textbox.TextMarginBottom = 0;
            this.password_textbox.TextMarginLeft = 3;
            this.password_textbox.TextMarginTop = 0;
            this.password_textbox.TextPlaceholder = "Enter Pasword";
            this.password_textbox.UseSystemPasswordChar = true;
            this.password_textbox.WordWrap = true;
            this.password_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.password_textbox_KeyDown);
            // 
            // firstName_textbox
            // 
            this.firstName_textbox.AcceptsReturn = false;
            this.firstName_textbox.AcceptsTab = false;
            this.firstName_textbox.AnimationSpeed = 200;
            this.firstName_textbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstName_textbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstName_textbox.BackColor = System.Drawing.Color.White;
            this.firstName_textbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstName_textbox.BackgroundImage")));
            this.firstName_textbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.firstName_textbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.firstName_textbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.firstName_textbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.firstName_textbox.BorderRadius = 10;
            this.firstName_textbox.BorderThickness = 1;
            this.firstName_textbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstName_textbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstName_textbox.DefaultFont = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.firstName_textbox.DefaultText = "";
            this.firstName_textbox.FillColor = System.Drawing.Color.White;
            this.firstName_textbox.ForeColor = System.Drawing.Color.DarkMagenta;
            this.firstName_textbox.HideSelection = true;
            this.firstName_textbox.IconLeft = null;
            this.firstName_textbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstName_textbox.IconPadding = 10;
            this.firstName_textbox.IconRight = null;
            this.firstName_textbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstName_textbox.Lines = new string[0];
            this.firstName_textbox.Location = new System.Drawing.Point(38, 73);
            this.firstName_textbox.MaxLength = 32767;
            this.firstName_textbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.firstName_textbox.Modified = false;
            this.firstName_textbox.Multiline = false;
            this.firstName_textbox.Name = "firstName_textbox";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstName_textbox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.firstName_textbox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstName_textbox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.DarkMagenta;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstName_textbox.OnIdleState = stateProperties28;
            this.firstName_textbox.Padding = new System.Windows.Forms.Padding(3);
            this.firstName_textbox.PasswordChar = '\0';
            this.firstName_textbox.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstName_textbox.PlaceholderText = "Enter First Name";
            this.firstName_textbox.ReadOnly = false;
            this.firstName_textbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstName_textbox.SelectedText = "";
            this.firstName_textbox.SelectionLength = 0;
            this.firstName_textbox.SelectionStart = 0;
            this.firstName_textbox.ShortcutsEnabled = true;
            this.firstName_textbox.Size = new System.Drawing.Size(234, 31);
            this.firstName_textbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.firstName_textbox.TabIndex = 0;
            this.firstName_textbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstName_textbox.TextMarginBottom = 0;
            this.firstName_textbox.TextMarginLeft = 3;
            this.firstName_textbox.TextMarginTop = 0;
            this.firstName_textbox.TextPlaceholder = "Enter First Name";
            this.firstName_textbox.UseSystemPasswordChar = false;
            this.firstName_textbox.WordWrap = true;
            this.firstName_textbox.KeyDown += new System.Windows.Forms.KeyEventHandler(this.firstName_textbox_KeyDown);
            // 
            // LogInFormEllips
            // 
            this.LogInFormEllips.ElipseRadius = 10;
            this.LogInFormEllips.TargetControl = this;
            // 
            // Minimize
            // 
            this.Minimize.ActiveImage = ((System.Drawing.Image)(resources.GetObject("Minimize.ActiveImage")));
            this.Minimize.AllowAnimations = true;
            this.Minimize.AllowBuffering = false;
            this.Minimize.AllowToggling = false;
            this.Minimize.AllowZooming = true;
            this.Minimize.AllowZoomingOnFocus = false;
            this.Minimize.BackColor = System.Drawing.Color.Transparent;
            this.Minimize.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Minimize.ErrorImage = ((System.Drawing.Image)(resources.GetObject("Minimize.ErrorImage")));
            this.Minimize.FadeWhenInactive = false;
            this.Minimize.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.Minimize.Image = ((System.Drawing.Image)(resources.GetObject("Minimize.Image")));
            this.Minimize.ImageActive = ((System.Drawing.Image)(resources.GetObject("Minimize.ImageActive")));
            this.Minimize.ImageLocation = null;
            this.Minimize.ImageMargin = 40;
            this.Minimize.ImageSize = new System.Drawing.Size(-20, -20);
            this.Minimize.ImageZoomSize = new System.Drawing.Size(20, 20);
            this.Minimize.InitialImage = ((System.Drawing.Image)(resources.GetObject("Minimize.InitialImage")));
            this.Minimize.Location = new System.Drawing.Point(38, 12);
            this.Minimize.Name = "Minimize";
            this.Minimize.Rotation = 0;
            this.Minimize.ShowActiveImage = true;
            this.Minimize.ShowCursorChanges = true;
            this.Minimize.ShowImageBorders = true;
            this.Minimize.ShowSizeMarkers = false;
            this.Minimize.Size = new System.Drawing.Size(20, 20);
            this.Minimize.TabIndex = 1;
            this.Minimize.ToolTipText = "";
            this.Minimize.WaitOnLoad = false;
            this.Minimize.Zoom = 40;
            this.Minimize.ZoomSpeed = 10;
            // 
            // Exit
            // 
            this.Exit.ActiveImage = ((System.Drawing.Image)(resources.GetObject("Exit.ActiveImage")));
            this.Exit.AllowAnimations = true;
            this.Exit.AllowBuffering = false;
            this.Exit.AllowToggling = false;
            this.Exit.AllowZooming = true;
            this.Exit.AllowZoomingOnFocus = true;
            this.Exit.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.Exit.AutoScrollMargin = new System.Drawing.Size(800, 450);
            this.Exit.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            this.Exit.BackColor = System.Drawing.Color.Transparent;
            this.Exit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Exit.ErrorImage = ((System.Drawing.Image)(resources.GetObject("Exit.ErrorImage")));
            this.Exit.FadeWhenInactive = false;
            this.Exit.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.Exit.Image = ((System.Drawing.Image)(resources.GetObject("Exit.Image")));
            this.Exit.ImageActive = ((System.Drawing.Image)(resources.GetObject("Exit.ImageActive")));
            this.Exit.ImageLocation = null;
            this.Exit.ImageMargin = 40;
            this.Exit.ImageSize = new System.Drawing.Size(-20, -20);
            this.Exit.ImageZoomSize = new System.Drawing.Size(20, 20);
            this.Exit.InitialImage = ((System.Drawing.Image)(resources.GetObject("Exit.InitialImage")));
            this.Exit.Location = new System.Drawing.Point(2, 12);
            this.Exit.Name = "Exit";
            this.Exit.Rotation = 0;
            this.Exit.ShowActiveImage = true;
            this.Exit.ShowCursorChanges = true;
            this.Exit.ShowImageBorders = true;
            this.Exit.ShowSizeMarkers = false;
            this.Exit.Size = new System.Drawing.Size(20, 20);
            this.Exit.TabIndex = 0;
            this.Exit.ToolTipText = "";
            this.Exit.WaitOnLoad = false;
            this.Exit.Zoom = 40;
            this.Exit.ZoomSpeed = 10;
            this.Exit.Click += new System.EventHandler(this.Exit_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.Minimize);
            this.panel2.Controls.Add(this.Exit);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(10, 10);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(621, 39);
            this.panel2.TabIndex = 2;
            // 
            // Customer_Signup
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.DarkMagenta;
            this.ClientSize = new System.Drawing.Size(641, 548);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.panel2);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Customer_Signup";
            this.Padding = new System.Windows.Forms.Padding(10);
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "0";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private Bunifu.Framework.UI.BunifuElipse LogInFormEllips;
        private Bunifu.UI.WinForms.BunifuImageButton Minimize;
        private Bunifu.UI.WinForms.BunifuImageButton Exit;
        private Bunifu.UI.WinForms.BunifuTextBox cpassword_textbox;
        private Bunifu.UI.WinForms.BunifuTextBox userid_textbox;
        private Bunifu.UI.WinForms.BunifuTextBox phone_textbox;
        private Bunifu.UI.WinForms.BunifuTextBox email_textbox;
        private System.Windows.Forms.Label Logo;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Clear;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton SignUpButton;
        private Bunifu.UI.WinForms.BunifuTextBox password_textbox;
        private Bunifu.UI.WinForms.BunifuTextBox firstName_textbox;
        private System.Windows.Forms.Label cpasswordErr;
        private System.Windows.Forms.Label passwordErr;
        private System.Windows.Forms.Label useridErr;
        private System.Windows.Forms.Label phoneErr;
        private System.Windows.Forms.Label emailErr;
        private System.Windows.Forms.Label firstNameErr;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton goto_login_Button;
        private System.Windows.Forms.Label lastNameErr;
        private Bunifu.UI.WinForms.BunifuTextBox lastName_textBox;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.DateTimePicker dobDatePicker;
        private System.Windows.Forms.Label dobErr;
    }
}